run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gocritic
    - gofmt
    - goimports
  disable:
    - exhaustive
    - wrapcheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocritic
