DROP TABLE IF EXISTS ingestions;
DROP TABLE IF EXISTS scores;
DROP TABLE IF EXISTS deltas;
DROP TABLE IF EXISTS baselines;
DROP TABLE IF EXISTS snapshots;
DROP TABLE IF EXISTS repositories;
DROP TABLE IF EXISTS tenants;
DROP EXTENSION IF EXISTS "pgcrypto";
